name: Bump Homebrew formula

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.HOMEBREW_TOKEN}}
          formula: kubecm