name: Bump Homebrew kubecm formula

on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3.1.1
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          formula: kubecm