name: Homebrew

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: kubecm
          homebrew-tap: sunny0826/homebrew-tap
          base-branch: master
          download-url: https://github.com/sunny0826/kubecm/releases/download/v${{version}}/kubecm_${{version}}_Darwin_x86_64.tar.gz
          commit-message: ${{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

